-- Run once in Supabase SQL Editor
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;

drop policy if exists "allow anonymous push subscription registration"
on public.push_subscriptions;

create policy "allow anonymous push subscription registration"
on public.push_subscriptions
for insert
to anon
with check (true);

drop policy if exists "allow anonymous push subscription update"
on public.push_subscriptions;

create policy "allow anonymous push subscription update"
on public.push_subscriptions
for update
to anon
using (true)
with check (true);

-- Important: intentionally do NOT add SELECT or DELETE policies for anon.
-- Browser clients can register/update their own subscription, but cannot read the list.
